// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uepjgrhvpyneesnoiphf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlcGpncmh2cHluZWVzbm9pcGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMTcxNDMsImV4cCI6MjA1Mjg5MzE0M30.QL6OVVINbL5h6J5nEjFqtXLYFDmyFmQPHH54Rc3D69Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);